feat(main): introduce a variable to set autosync
camptocamp/devops-stack-module-argocd pull request #18
Opened 2022-12-07 09:33 UTC by Xaving

autosync in argocd is set to false by default

This feature has been test on a scaleway instance

2022-12-09 08:32 UTC, lentidas requested changes

2022-12-09 08:32 UTC, lentidas commented on variables.tf
> +}
Same comment as here: https://github.com/camptocamp/devops-stack-module-traefik/pull/25#discussion_r1044200571

2022-12-09 09:55 UTC, lentidas approved these changes

2022-12-09 09:55 UTC, lentidas commented on variables.tf
> +}
After discussion, will leave as is for now. These changes are urgently needed for Scaleway.

2022-12-14 11:05 UTC, cryptobioz approved these changes

2022-12-15 14:14 UTC, fsismondi commented
@Xaving should we merge?

2022-12-16 09:31 UTC, merged